/**
 * Table registry: maps content modules to physical tables + column types.
 * Used by the generic data layer to build type-safe, cast-correct SQL.
 */

export type ColType = 'text' | 'int' | 'numeric' | 'bool' | 'date' | 'timestamptz' | 'jsonb';

export interface ColumnSpec {
  type: ColType;
  /** writable from the CMS layer (else DB-managed) */
  writable?: boolean;
  /** store as NULL instead of the type zero-value when empty */
  nullable?: boolean;
}

export interface TableSpec {
  table: string;
  pk: string;
  columns: Record<string, ColumnSpec>;
  /** maintained timestamps (created_at/updated_at) handled automatically */
  timestamps?: boolean;
  idPrefix?: string;
}

const t = (opts: Partial<ColumnSpec> = {}): ColumnSpec => ({ type: 'text', writable: true, nullable: true, ...opts });
const n = (opts: Partial<ColumnSpec> = {}): ColumnSpec => ({ type: 'int', writable: true, nullable: true, ...opts });
const b = (opts: Partial<ColumnSpec> = {}): ColumnSpec => ({ type: 'bool', writable: true, nullable: false, ...opts });
const j = (opts: Partial<ColumnSpec> = {}): ColumnSpec => ({ type: 'jsonb', writable: true, nullable: false, ...opts });
const d = (opts: Partial<ColumnSpec> = {}): ColumnSpec => ({ type: 'date', writable: true, nullable: true, ...opts });

const tableDefs = {
  site_setting: {
    table: 'site_setting',
    pk: 'key',
    idPrefix: 'set',
    columns: {
      key: t(),
      value: j(),
      type: t(),
      group: t(),
      label: t(),
      help: t(),
      options: j(),
      is_public: b(),
      sort_order: n(),
    },
  },
  social_link: {
    table: 'social_link',
    pk: 'id',
    idPrefix: 'soc',
    timestamps: true,
    columns: {
      network: t({ nullable: false }),
      label: t(),
      url: t({ nullable: false }),
      handle: t(),
      icon: t(),
      placements: j(),
      is_verified: b(),
      status: t(),
      sort_order: n(),
    },
  },
  navigation_item: {
    table: 'navigation_item',
    pk: 'id',
    idPrefix: 'nav',
    timestamps: true,
    columns: {
      location: t({ nullable: false }),
      label: t({ nullable: false }),
      href: t({ nullable: false }),
      parent_id: t(),
      description: t(),
      is_external: b(),
      open_new_tab: b(),
      is_visible: b(),
      badge: t(),
      sort_order: n(),
    },
  },
  page: {
    table: 'page',
    pk: 'id',
    idPrefix: 'pg',
    timestamps: true,
    columns: {
      slug: t({ nullable: false }),
      title: t({ nullable: false }),
      nav_label: t(),
      surface: t(),
      status: t(),
      description: t(),
      seo: j(),
      published_at: { type: 'timestamptz', writable: true, nullable: true },
    },
  },
  content_block: {
    table: 'content_block',
    pk: 'id',
    idPrefix: 'blk',
    timestamps: true,
    columns: {
      block_type: t({ nullable: false }),
      name: t({ nullable: false }),
      headline: t(),
      eyebrow: t(),
      body: t(),
      props: j(),
      media: j(),
      links: j(),
      status: t(),
      is_sample: b(),
    },
  },
  page_block: {
    table: 'page_block',
    pk: 'block_id',
    columns: {
      page_id: t(),
      block_id: t(),
      placement: t(),
      variant: t(),
      sort_order: n(),
      is_visible: b(),
      overrides: j(),
    },
  },
  service: {
    table: 'service',
    pk: 'id',
    idPrefix: 'svc',
    timestamps: true,
    columns: {
      slug: t({ nullable: false }),
      division: t(),
      title: t({ nullable: false }),
      summary: t(),
      description: t(),
      icon: t(),
      bullets: j(),
      deliverables: j(),
      tools: j(),
      process: j(),
      price_note: t(),
      cta_label: t(),
      cta_href: t(),
      hero_asset: t(),
      is_featured: b(),
      is_sample: b(),
      status: t(),
      sort_order: n(),
      seo: j(),
    },
  },
  project: {
    table: 'project',
    pk: 'id',
    idPrefix: 'prj',
    timestamps: true,
    columns: {
      slug: t({ nullable: false }),
      division: t({ nullable: false }),
      title: t({ nullable: false }),
      category: t(),
      form: t(),
      summary: t(),
      client: t(),
      client_public: b(),
      role: t(),
      problem: t(),
      solution: t(),
      outcomes: j(),
      technologies: j(),
      services: j(),
      tools: j(),
      deliverables: j(),
      location: t(),
      event_date: d(),
      year: n(),
      duration_label: t(),
      budget_band: t(),
      repo_url: t(),
      live_url: t(),
      case_study_url: t(),
      external_links: j(),
      gallery: j(),
      cover_asset_id: t(),
      hero_video_id: t(),
      accent: t(),
      credits: j(),
      metrics: j(),
      is_featured: b(),
      is_sample: b(),
      status: t(),
      published_at: { type: 'timestamptz', writable: true, nullable: true },
      sort_order: n(),
      seo: j(),
    },
  },
  media_asset: {
    table: 'media_asset',
    pk: 'id',
    idPrefix: 'ast',
    timestamps: true,
    columns: {
      public_id: t(),
      url: t(),
      kind: t(),
      mime_type: t(),
      filename: t(),
      title: t(),
      alt: t(),
      caption: t(),
      credit: t(),
      folder: t(),
      tags: j(),
      bytes: n(),
      width: n(),
      height: n(),
      duration_s: { type: 'numeric', writable: true, nullable: true },
      checksum: t(),
      storage: t(),
      variants: j(),
      blur_data: t(),
      is_referenced: b(),
      uploaded_by: t(),
    },
  },
  media_video: {
    table: 'media_video',
    pk: 'id',
    idPrefix: 'vid',
    timestamps: true,
    columns: {
      title: t({ nullable: false }),
      description: t(),
      source: t({ nullable: false }),
      source_id: t(),
      source_url: t(),
      embed_url: t(),
      file_asset_id: t(),
      poster_asset_id: t(),
      poster_url: t(),
      project_id: t(),
      category: t(),
      form: t(),
      client: t(),
      shot_on: d(),
      duration_s: n(),
      services: j(),
      tools: j(),
      tags: j(),
      embed_config: j(),
      metadata_state: t(),
      metadata: j(),
      external_url: t(),
      is_featured: b(),
      is_sample: b(),
      status: t(),
      published_at: { type: 'timestamptz', writable: true, nullable: true },
      sort_order: n(),
      seo: j(),
    },
  },
  gallery: {
    table: 'gallery',
    pk: 'id',
    idPrefix: 'gal',
    timestamps: true,
    columns: {
      slug: t({ nullable: false }),
      title: t({ nullable: false }),
      description: t(),
      kind: t(),
      division: t(),
      project_id: t(),
      items: j(),
      is_featured: b(),
      is_sample: b(),
      status: t(),
      sort_order: n(),
    },
  },
  testimonial: {
    table: 'testimonial',
    pk: 'id',
    idPrefix: 'tst',
    timestamps: true,
    columns: {
      quote: t({ nullable: false }),
      author_name: t(),
      author_role: t(),
      author_org: t(),
      location: t(),
      avatar_asset_id: t(),
      division: t(),
      project_id: t(),
      rating: n(),
      is_sample: b(),
      source_note: t(),
      approved_at: { type: 'timestamptz', writable: true, nullable: true },
      is_featured: b(),
      status: t(),
      sort_order: n(),
    },
  },
  team_member: {
    table: 'team_member',
    pk: 'id',
    idPrefix: 'tm',
    timestamps: true,
    columns: {
      name: t({ nullable: false }),
      role: t(),
      bio: t(),
      is_founder: b(),
      is_placeholder: b(),
      division: t(),
      focus: j(),
      avatar_asset_id: t(),
      links: j(),
      is_visible: b(),
      sort_order: n(),
      status: t(),
    },
  },
  blog_post: {
    table: 'blog_post',
    pk: 'id',
    idPrefix: 'post',
    timestamps: true,
    columns: {
      slug: t({ nullable: false }),
      title: t({ nullable: false }),
      excerpt: t(),
      body: t(),
      body_html: t(),
      cover_asset_id: t(),
      author_user_id: t(),
      author_name: t(),
      division: t(),
      category: t(),
      tags: j(),
      related_project_ids: j(),
      reading_minutes: n(),
      is_sample: b(),
      is_featured: b(),
      status: t(),
      published_at: { type: 'timestamptz', writable: true, nullable: true },
      scheduled_at: { type: 'timestamptz', writable: true, nullable: true },
      seo: j(),
    },
  },
  skill: {
    table: 'skill',
    pk: 'id',
    idPrefix: 'skl',
    timestamps: true,
    columns: {
      name: t({ nullable: false }),
      slug: t({ nullable: false }),
      category: t(),
      level: n(),
      confidence: n(),
      description: t(),
      years_start: n(),
      evidence: t(),
      icon: t(),
      division: t(),
      is_featured: b(),
      is_sample: b(),
      status: t(),
      sort_order: n(),
    },
  },
  experience_item: {
    table: 'experience_item',
    pk: 'id',
    idPrefix: 'exp',
    timestamps: true,
    columns: {
      role: t({ nullable: false }),
      organization: t(),
      location: t(),
      summary: t(),
      bullets: j(),
      technologies: j(),
      highlights: j(),
      start_date: d(),
      start_label: t(),
      end_date: d(),
      end_label: t(),
      is_current: b(),
      kind: t(),
      project_ids: j(),
      is_sample: b(),
      status: t(),
      sort_order: n(),
    },
  },
  certification: {
    table: 'certification',
    pk: 'id',
    idPrefix: 'cert',
    timestamps: true,
    columns: {
      name: t({ nullable: false }),
      issuer: t(),
      credential_id: t(),
      verify_url: t(),
      status: t(),
      completed: b(),
      issued_on: d(),
      expires_on: d(),
      description: t(),
      division: t(),
      is_sample: b(),
      sort_order: n(),
      status_label_override: t(),
    },
  },
  resume_version: {
    table: 'resume_version',
    pk: 'id',
    idPrefix: 'rsm',
    timestamps: true,
    columns: {
      label: t({ nullable: false }),
      version: t(),
      asset_id: t(),
      filename: t(),
      bytes: n(),
      is_active: b(),
      published_at: { type: 'timestamptz', writable: true, nullable: true },
      notes: t(),
    },
  },
  pricing_package: {
    table: 'pricing_package',
    pk: 'id',
    idPrefix: 'pkg',
    timestamps: true,
    columns: {
      division: t(),
      name: t({ nullable: false }),
      tagline: t(),
      mode: t(),
      amount: { type: 'numeric', writable: true, nullable: true },
      currency: t(),
      period: t(),
      includes: j(),
      exclusions: j(),
      turnaround: t(),
      notes: t(),
      is_featured: b(),
      is_sample: b(),
      status: t(),
      sort_order: n(),
    },
  },
  contact_submission: {
    table: 'contact_submission',
    pk: 'id',
    idPrefix: 'sub',
    timestamps: false,
    columns: {
      form: t(),
      name: t(),
      email: t(),
      phone: t(),
      organization: t(),
      service: t(),
      project_type: t(),
      event_date: d(),
      location: t(),
      budget_band: t(),
      timeline: t(),
      requirements: t(),
      message: t(),
      page_path: t(),
      user_agent: t(),
      ip_hash: t(),
      consent: b(),
      status: t(),
      notified_at: { type: 'timestamptz', writable: true, nullable: true },
      meta: j(),
      created_at: { type: 'timestamptz', writable: false, nullable: true },
    },
  },
  seo_record: {
    table: 'seo_record',
    pk: 'id',
    idPrefix: 'seo',
    timestamps: false,
    columns: {
      scope: t(),
      title: t(),
      title_template: t(),
      description: t(),
      keywords: j(),
      canonical: t(),
      og_asset_id: t(),
      og_title: t(),
      og_description: t(),
      twitter_card: t(),
      robots: t(),
      no_index: b(),
      structured_type: t(),
      extra: j(),
      updated_at: { type: 'timestamptz', writable: false, nullable: true },
    },
  },
  admin_user: {
    table: 'admin_user',
    pk: 'id',
    idPrefix: 'usr',
    timestamps: true,
    columns: {
      email: t(),
      name: t(),
      title: t(),
      password_hash: t({ writable: false }),
      role: t(),
      status: t(),
      email_verified: b(),
      last_login_at: { type: 'timestamptz', writable: false, nullable: true },
      password_set_at: { type: 'timestamptz', writable: false, nullable: true },
      failed_attempts: n({ writable: false }),
      locked_until: { type: 'timestamptz', writable: false, nullable: true },
    },
  },
  admin_session: {
    table: 'admin_session',
    pk: 'id',
    idPrefix: 'ses',
    timestamps: false,
    columns: {
      user_id: t(),
      token_hash: t(),
      ip: t(),
      user_agent: t(),
      expires_at: { type: 'timestamptz', writable: true, nullable: false },
      revoked_at: { type: 'timestamptz', writable: true, nullable: true },
      created_at: { type: 'timestamptz', writable: true, nullable: true },
    },
  },
  audit_log: {
    table: 'audit_log',
    pk: 'id',
    idPrefix: 'aud',
    timestamps: false,
    columns: {
      user_id: t(),
      action: t(),
      module: t(),
      entity: t(),
      entity_id: t(),
      summary: t(),
      meta: j(),
      ip: t(),
      created_at: { type: 'timestamptz', writable: true, nullable: true },
    },
  },
  cm_event: {
    table: 'cm_event',
    pk: 'id',
    idPrefix: 'evt',
    columns: {
      name: t({ nullable: false }),
      path: t(),
      target: t(),
      division: t(),
      visitor_id: t(),
      meta: j(),
      created_at: { type: 'timestamptz', writable: true, nullable: true },
    },
  },
  admin_role: {
    table: 'admin_role',
    pk: 'id',
    idPrefix: 'role',
    timestamps: true,
    columns: {
      key: t(),
      label: t(),
      description: t(),
      permissions: j(),
      is_system: b(),
    },
  },
} satisfies Record<string, TableSpec>;

export const TABLES: { [K in keyof typeof tableDefs]: TableSpec } = tableDefs;

export type TableName = keyof typeof tableDefs;
