/**
 * Covenant CMS — module registry.
 *
 * One entry per CMS module listed in the PRD (§9). Each entry declares the
 * backing table, the editable fields, list columns, filters and behaviour.
 * The admin shell, the generic CRUD API and validation are all derived from
 * this registry, so adding a field or a whole module is a data change.
 */

import type { TableName } from '../db/tables';
import type { FieldDef } from './fields';
import {
  BUDGET_BANDS,
  CERTIFICATION_STATUSES,
  CURRENCY_OPTIONS,
  DIVISION_OPTIONS,
  EMBED_SOURCES,
  EXPERIENCE_KINDS,
  MEDIA_CATEGORIES,
  MEDIA_SERVICE_OPTIONS,
  NAV_LOCATIONS,
  PORTFOLIO_DIVISION_OPTIONS,
  PRICING_MODES,
  PRICING_PERIODS,
  PUBLISH_OPTIONS,
  SKILL_CATEGORIES,
  SOCIAL_NETWORKS,
  SOCIAL_PLACEMENTS,
  STATUS_OPTIONS,
  TECH_BUDGET_BANDS,
  TECH_CATEGORIES,
  TECH_PROJECT_TYPE_OPTIONS,
  TIMELINE_OPTIONS,
  VIDEO_FORM_OPTIONS,
} from './options';

export type ModuleGroup = 'Structure' | 'Brand' | 'Media' | 'Technology' | 'Trust' | 'Commerce' | 'Insight' | 'System';

export const seoField = (label = 'SEO'): FieldDef => ({
  key: 'seo',
  label,
  type: 'seo',
  group: 'seo',
  help: 'Overrides the page default. Leave blank to inherit from Site SEO settings.',
});

const text = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'text',
  ...extra,
});
const area = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'textarea',
  rows: 4,
  ...extra,
});
const bool = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'boolean',
  width: 'third',
  ...extra,
});
const num = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'number',
  width: 'third',
  ...extra,
});
const list = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'list',
  ...extra,
});
const tags = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'tags',
  ...extra,
});
const slug = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'slug',
  width: 'half',
  ...extra,
});
const statusField = (options: readonly { value: string; label: string }[] = STATUS_OPTIONS): FieldDef => ({
  key: 'status',
  label: 'Publishing status',
  type: 'select',
  width: 'third',
  default: 'draft',
  options: options.map((o) => ({ value: o.value, label: o.label })),
});
const orderField: FieldDef = {
  key: 'sort_order',
  label: 'Order',
  type: 'number',
  width: 'third',
  default: 0,
  help: 'Lower numbers appear first. Drag-and-drop in the list also sets this.',
};
const featuredField = (label = 'Featured'): FieldDef => ({
  key: 'is_featured',
  label,
  type: 'boolean',
  width: 'third',
  help: 'Featured items are surfaced on homepages and highlight sections.',
});
const sampleField = (label = 'Placeholder content'): FieldDef => ({
  key: 'is_sample',
  label,
  type: 'boolean',
  width: 'third',
  help: 'Marks this record as seeded placeholder copy. The public site shows a "sample" tag so nothing here is ever mistaken for a real client result.',
});
const imageField = (key: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({
  key,
  label,
  type: 'image',
  width: 'half',
  ...extra,
});

const externalLinkFields: FieldDef[] = [
  text('label', 'Label', { required: true, maxLength: 60 }),
  { key: 'url', label: 'URL', type: 'url', required: true },
  {
    key: 'kind',
    label: 'Kind',
    type: 'select',
    options: [
      { value: 'live', label: 'Live / published' },
      { value: 'repo', label: 'Repository' },
      { value: 'social', label: 'Social post' },
      { value: 'press', label: 'Press / feature' },
      { value: 'other', label: 'Other' },
    ],
    default: 'other',
  },
];

const galleryItemFields: FieldDef[] = [
  { key: 'asset_id', label: 'Image', type: 'image', required: true },
  text('caption', 'Caption', { maxLength: 160 }),
  text('alt', 'Alt text', { maxLength: 180, help: 'Describe the image for screen readers.' }),
];

export interface ListColumn {
  key: string;
  label: string;
  type?: 'text' | 'status' | 'bool' | 'number' | 'date' | 'image' | 'tag' | 'relation';
  width?: string;
}

export type AdminEditor =
  | 'collection'
  | 'media-library'
  | 'videos'
  | 'projects'
  | 'navigation'
  | 'settings'
  | 'seo'
  | 'resume'
  | 'submissions'
  | 'featured'
  | 'blocks';

export interface CmsModuleDef {
  key: string;
  label: string;
  singular: string;
  group: ModuleGroup;
  icon: string;
  description: string;
  table: TableName;
  editor: AdminEditor;
  fields: FieldDef[];
  primary: string;
  secondary?: string;
  previewImage?: string;
  columns: ListColumn[];
  search?: string[];
  /** values forced on every record (e.g. division scoping) */
  fixed?: Record<string, unknown>;
  /** column filters shown above the list */
  filterBy?: { key: string; label: string; options: readonly { value: string; label: string }[] } | { key: string; label: string; options: readonly { value: string; label: string }[] }[];
  sortable?: boolean;
  publishable?: boolean;
  slugFrom?: string;
  /** prefix used to build "View on site" links */
  publicBase?: string;
  emptyTitle?: string;
  emptyHint?: string;
  /** permission module key (defaults to key) */
  permission?: string;
  duplicate?: boolean;
  /** admin list query: extra SQL where fragment bound with fixed params (server-only) */
  defaultSort?: string;
}

const divisionFilter = { key: 'division', label: 'Division', options: DIVISION_OPTIONS };

export const CMS_MODULES: CmsModuleDef[] = [
  // ── Structure ──────────────────────────────────────────────────────────────
  {
    key: 'pages',
    label: 'Pages',
    singular: 'Page',
    group: 'Structure',
    icon: 'pages',
    description: 'Every public page. Slug controls the URL; published pages appear in navigation candidates and the sitemap.',
    table: 'page',
    editor: 'collection',
    primary: 'title',
    secondary: 'slug',
    sortable: false,
    publishable: true,
    slugFrom: 'title',
    columns: [
      { key: 'title', label: 'Page', type: 'text' },
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'surface', label: 'Experience', type: 'tag' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'slug', 'description'],
    defaultSort: 'ORDER BY surface ASC, slug ASC',
    fields: [
      text('title', 'Title', { required: true, maxLength: 120 }),
      slug('slug', 'Slug', { required: true, help: 'Use "home" for the main homepage, or paths like "media/work".', placeholder: 'about' }),
      {
        key: 'surface',
        label: 'Experience',
        type: 'select',
        width: 'third',
        default: 'main',
        options: [
          { value: 'main', label: 'Main brand' },
          { value: 'media', label: 'Media portfolio' },
          { value: 'tech', label: 'Tech portfolio' },
        ],
      },
      text('nav_label', 'Navigation label', { width: 'third', maxLength: 40 }),
      statusField(),
      area('description', 'Short description', { maxLength: 300, help: 'Used in listings and as the meta description fallback.' }),
      seoField(),
    ],
  },
  {
    key: 'blocks',
    label: 'Homepage sections',
    singular: 'Section',
    group: 'Structure',
    icon: 'sections',
    description: 'Reusable, CMS-composed sections. Attach any section to any page and reorder it — no code edits required.',
    table: 'content_block',
    editor: 'blocks',
    primary: 'name',
    secondary: 'block_type',
    publishable: true,
    sortable: false,
    columns: [
      { key: 'name', label: 'Section', type: 'text' },
      { key: 'block_type', label: 'Type', type: 'tag' },
      { key: 'headline', label: 'Headline', type: 'text' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['name', 'headline', 'body'],
    defaultSort: 'ORDER BY block_type ASC, updated_at DESC',
    emptyTitle: 'No sections yet',
    emptyHint: 'Sections are the building blocks of every homepage and landing page.',
    fields: [
      text('name', 'Internal name', { required: true, maxLength: 90, help: 'Only visible to you in the CMS.' }),
      {
        key: 'block_type',
        label: 'Section type',
        type: 'select',
        required: true,
        width: 'half',
        options: [
          { value: 'hero_brand', label: 'Brand hero (two-world)' },
          { value: 'hero_media', label: 'Media hero (floating videos)' },
          { value: 'hero_tech', label: 'Tech hero (portrait)' },
          { value: 'two_worlds', label: 'Two worlds — media vs tech' },
          { value: 'statement', label: 'Statement / manifesto' },
          { value: 'service_grid', label: 'Service grid' },
          { value: 'project_grid', label: 'Work / case study grid' },
          { value: 'video_wall', label: 'Video wall' },
          { value: 'photo_strip', label: 'Photo strip / gallery' },
          { value: 'process_timeline', label: 'Process timeline' },
          { value: 'skill_matrix', label: 'Skill matrix' },
          { value: 'experience_timeline', label: 'Experience timeline' },
          { value: 'testimonial_wall', label: 'Testimonials' },
          { value: 'pricing_table', label: 'Pricing' },
          { value: 'logo_marquee', label: 'Marquee band' },
          { value: 'stats_band', label: 'Stats band' },
          { value: 'about_split', label: 'About — split media' },
          { value: 'team_grid', label: 'Team grid' },
          { value: 'blog_preview', label: 'Blog preview' },
          { value: 'contact_block', label: 'Contact / CTA block' },
          { value: 'rich_text', label: 'Rich text page body' },
          { value: 'certifications', label: 'Certifications' },
          { value: 'tools_grid', label: 'Tools grid' },
          { value: 'resume_block', label: 'Resume download' },
          { value: 'faq', label: 'FAQ' },
        ],
      },
      statusField(),
      text('eyebrow', 'Eyebrow label', { width: 'half', maxLength: 60 }),
      text('headline', 'Headline', { maxLength: 160 }),
      area('body', 'Body copy', { rows: 6, maxLength: 2000 }),
      { key: 'props', label: 'Section options', type: 'json', group: 'options', help: 'Advanced overrides merged over the section defaults (JSON).' },
      {
        key: 'media',
        label: 'Attached media',
        type: 'repeat',
        group: 'media',
        itemLabel: 'Item',
        itemFields: [
          { key: 'asset_id', label: 'Image', type: 'image' },
          { key: 'video_id', label: 'Video', type: 'relation', module: 'videos' },
          { key: 'role', label: 'Role', type: 'select', options: [{ value: 'primary', label: 'Primary' }, { value: 'secondary', label: 'Secondary' }, { value: 'background', label: 'Background' }], default: 'primary' },
          text('caption', 'Caption', { maxLength: 160 }),
          text('alt', 'Alt text', { maxLength: 180 }),
        ],
      },
      {
        key: 'links',
        label: 'Buttons / links',
        type: 'repeat',
        group: 'links',
        itemLabel: 'Button',
        max: 4,
        itemFields: [
          text('label', 'Label', { required: true, maxLength: 40 }),
          { key: 'href', label: 'Link', type: 'url', required: true },
          { key: 'variant', label: 'Style', type: 'select', options: [{ value: 'primary', label: 'Primary' }, { value: 'ghost', label: 'Ghost' }, { value: 'link', label: 'Text link' }], default: 'primary' },
        ],
      },
      sampleField('Seeded placeholder'),
    ],
  },
  {
    key: 'navigation',
    label: 'Navigation',
    singular: 'Navigation item',
    group: 'Structure',
    icon: 'navigation',
    description: 'Header and footer menus for all three experiences, ordered here.',
    table: 'navigation_item',
    editor: 'navigation',
    primary: 'label',
    secondary: 'href',
    sortable: true,
    columns: [
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'href', label: 'Target', type: 'text' },
      { key: 'is_visible', label: 'Visible', type: 'bool' },
    ],
    search: ['label', 'href'],
    fields: [
      text('label', 'Label', { required: true, maxLength: 40 }),
      { key: 'href', label: 'Link', type: 'url', required: true, placeholder: '/media/work' },
      {
        key: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        width: 'half',
        options: NAV_LOCATIONS.map((o) => ({ value: o.value, label: o.label })),
      },
      { key: 'parent_id', label: 'Parent item', type: 'relation', module: 'navigation', width: 'half' },
      bool('is_visible', 'Visible', { default: true }),
      bool('is_external', 'External link', { default: false }),
      bool('open_new_tab', 'Open in new tab', { default: false }),
      text('badge', 'Badge', { width: 'third', maxLength: 16, help: 'Small pill next to the label, e.g. "New".' }),
      area('description', 'Description', { rows: 2, maxLength: 160 }),
      orderField,
    ],
  },

  // ── Brand ──────────────────────────────────────────────────────────────────
  {
    key: 'settings',
    label: 'Site settings',
    singular: 'Setting',
    group: 'Brand',
    icon: 'settings',
    description: 'Brand copy, contact details, social handles, form behaviour and analytics.',
    table: 'site_setting',
    editor: 'settings',
    primary: 'label',
    columns: [{ key: 'key', label: 'Key', type: 'text' }],
    fields: [text('key', 'Key', { required: true })],
  },
  {
    key: 'social_links',
    label: 'Social links',
    singular: 'Social link',
    group: 'Brand',
    icon: 'share',
    description: 'Where Covenant exists online. Unverified links are held back from the public site.',
    table: 'social_link',
    editor: 'collection',
    primary: 'network',
    secondary: 'url',
    sortable: true,
    publishable: false,
    columns: [
      { key: 'network', label: 'Network', type: 'tag' },
      { key: 'url', label: 'URL', type: 'text' },
      { key: 'is_verified', label: 'Verified', type: 'bool' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['network', 'url', 'handle'],
    fields: [
      { key: 'network', label: 'Network', type: 'select', required: true, width: 'half', options: SOCIAL_NETWORKS.map((o) => ({ value: o.value, label: o.label })) },
      text('label', 'Display label', { width: 'half', maxLength: 40 }),
      { key: 'url', label: 'URL', type: 'url', required: true, placeholder: 'https://www.tiktok.com/@handle' },
      text('handle', 'Handle', { width: 'half', maxLength: 60, placeholder: '@covenantmedia' }),
      {
        key: 'placements',
        label: 'Shown in',
        type: 'multiselect',
        default: ['main'],
        options: SOCIAL_PLACEMENTS.map((o) => ({ value: o.value, label: o.label })),
      },
      bool('is_verified', 'Verified by me', { default: false, help: 'Only verified links render publicly — the PRD requires checking provisional URLs before launch.' }),
      statusField(PUBLISH_OPTIONS),
      orderField,
    ],
    emptyHint: 'Add and verify your profiles before launch.',
  },
  {
    key: 'services',
    label: 'Services',
    singular: 'Service',
    group: 'Brand',
    icon: 'services',
    description: 'Broad service categories for the brand site plus detailed offers on the Media and Tech portfolios.',
    table: 'service',
    editor: 'collection',
    primary: 'title',
    secondary: 'summary',
    previewImage: 'hero_asset',
    sortable: true,
    publishable: true,
    slugFrom: 'title',
    filterBy: divisionFilter,
    columns: [
      { key: 'title', label: 'Service', type: 'text' },
      { key: 'division', label: 'Division', type: 'tag' },
      { key: 'is_featured', label: 'Featured', type: 'bool' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'summary', 'description'],
    publicBase: '/services/',
    fields: [
      text('title', 'Title', { required: true, maxLength: 80 }),
      slug('slug', 'Slug', { required: true }),
      { key: 'division', label: 'Division', type: 'select', required: true, width: 'third', default: 'main', options: DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      statusField(),
      featuredField(),
      orderField,
      area('summary', 'Summary', { maxLength: 240, rows: 3, help: 'One or two sentences shown on cards.' }),
      { key: 'description', label: 'Full description', type: 'markdown', rows: 10, group: 'content' },
      list('bullets', 'Key points', { group: 'content', help: 'One per line.' }),
      list('deliverables', 'Deliverables', { group: 'content' }),
      tags('tools', 'Tools', { group: 'content' }),
      {
        key: 'process',
        label: 'Process steps',
        type: 'repeat',
        group: 'content',
        itemLabel: 'Step',
        max: 8,
        itemFields: [
          text('title', 'Step', { required: true, maxLength: 60 }),
          text('description', 'What happens', { maxLength: 240 }),
          text('duration', 'Typical duration', { maxLength: 40 }),
        ],
      },
      text('price_note', 'Pricing note', { group: 'pricing', maxLength: 160, help: 'Free text only — never an invented number. Leave blank to show "Request a quote".' }),
      text('cta_label', 'CTA label', { width: 'half', group: 'links', maxLength: 30 }),
      text('cta_href', 'CTA link', { width: 'half', group: 'links' }),
      imageField('hero_asset', 'Card image', { group: 'media' }),
      sampleField(),
      seoField(),
    ],
  },
  {
    key: 'team',
    label: 'Team',
    singular: 'Team member',
    group: 'Trust',
    icon: 'team',
    description: 'Covenant plus collaborators. Placeholders are labelled so no invented people appear publicly.',
    table: 'team_member',
    editor: 'collection',
    primary: 'name',
    secondary: 'role',
    previewImage: 'avatar_asset_id',
    sortable: true,
    columns: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'division', label: 'Division', type: 'tag' },
      { key: 'is_placeholder', label: 'Placeholder', type: 'bool' },
    ],
    search: ['name', 'role', 'bio'],
    emptyHint: 'Add collaborators as your crew grows.',
    fields: [
      text('name', 'Name', { required: true, maxLength: 80 }),
      text('role', 'Role / discipline', { width: 'half', maxLength: 80 }),
      { key: 'division', label: 'Appears in', type: 'select', width: 'third', default: 'main', options: DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      bool('is_founder', 'Founder', { width: 'third' }),
      bool('is_placeholder', 'Placeholder (not a real person)', { default: true, help: 'Keeps a clearly-labelled slot in the layout without inventing a person. Turn off when you add a real collaborator.' }),
      area('bio', 'Short bio', { maxLength: 600, rows: 5 }),
      tags('focus', 'Focus areas', { help: 'e.g. directing, drone, audio.' }),
      imageField('avatar_asset_id', 'Portrait'),
      {
        key: 'links',
        label: 'Links',
        type: 'repeat',
        itemLabel: 'Link',
        max: 6,
        itemFields: externalLinkFields,
      },
      bool('is_visible', 'Visible', { default: true, width: 'third' }),
      statusField(),
      orderField,
    ],
  },
  {
    key: 'testimonials',
    label: 'Testimonials',
    singular: 'Testimonial',
    group: 'Trust',
    icon: 'quote',
    description: 'Only genuine quotes. Seeded records are marked as samples and never render as real client statements.',
    table: 'testimonial',
    editor: 'collection',
    primary: 'quote',
    secondary: 'author_name',
    previewImage: 'avatar_asset_id',
    sortable: true,
    publishable: true,
    filterBy: { key: 'division', label: 'Division', options: DIVISION_OPTIONS },
    columns: [
      { key: 'quote', label: 'Quote', type: 'text' },
      { key: 'author_name', label: 'Author', type: 'text' },
      { key: 'division', label: 'Division', type: 'tag' },
      { key: 'is_sample', label: 'Sample', type: 'bool' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['quote', 'author_name', 'author_org'],
    fields: [
      area('quote', 'Quote', { required: true, rows: 4, maxLength: 600 }),
      text('author_name', 'Author name', { width: 'half', maxLength: 80 }),
      text('author_role', 'Author role', { width: 'half', maxLength: 80 }),
      text('author_org', 'Organisation', { width: 'half', maxLength: 80 }),
      text('location', 'Location', { width: 'half', maxLength: 80 }),
      imageField('avatar_asset_id', 'Avatar'),
      { key: 'division', label: 'Appears in', type: 'select', width: 'third', default: 'main', options: DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'project_id', label: 'Related project', type: 'relation', module: 'media_projects', width: 'half' },
      num('rating', 'Rating', { min: 1, max: 5, width: 'third' }),
      area('source_note', 'Source / proof', { rows: 2, maxLength: 240, help: 'Where this came from (DM, email, invoice note). Keeps the audit trail honest.' }),
      { key: 'approved_at', label: 'Approved on', type: 'date', width: 'third', help: 'Set when you confirmed the quote is genuine.' },
      bool('is_sample', 'Sample / placeholder', { width: 'third', help: 'When on, the public site labels the quote as sample content.' }),
      featuredField(),
      statusField(),
      orderField,
    ],
    emptyHint: 'No real testimonials yet — that is fine. Add them as clients reply.',
  },

  // ── Media ──────────────────────────────────────────────────────────────────
  {
    key: 'media_projects',
    label: 'Media projects',
    singular: 'Media project',
    group: 'Media',
    icon: 'film',
    description: 'Every media engagement: films, shoots, coverage, edits. Ordered and featured from here.',
    table: 'project',
    editor: 'projects',
    primary: 'title',
    secondary: 'client',
    previewImage: 'cover_asset_id',
    sortable: true,
    publishable: true,
    slugFrom: 'title',
    duplicate: true,
    fixed: { division: 'media' },
    filterBy: [
      { key: 'category', label: 'Category', options: MEDIA_CATEGORIES },
      { key: 'form', label: 'Format', options: VIDEO_FORM_OPTIONS },
    ],
    columns: [
      { key: 'title', label: 'Project', type: 'text' },
      { key: 'category', label: 'Category', type: 'tag' },
      { key: 'year', label: 'Year', type: 'number' },
      { key: 'is_featured', label: 'Featured', type: 'bool' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'summary', 'client'],
    publicBase: '/media/work/',
    emptyTitle: 'No media projects yet',
    emptyHint: 'Add a project, then paste YouTube / TikTok / Facebook links into it.',
    fields: [
      text('title', 'Title', { required: true, maxLength: 120 }),
      slug('slug', 'Slug', { required: true }),
      { key: 'division', label: 'Portfolio', type: 'select', required: true, width: 'third', default: 'media', options: PORTFOLIO_DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'category', label: 'Category', type: 'select', width: 'third', options: MEDIA_CATEGORIES.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'form', label: 'Format', type: 'select', width: 'third', options: VIDEO_FORM_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      statusField(),
      featuredField(),
      orderField,
      area('summary', 'One-line summary', { maxLength: 260, rows: 3, group: 'content' }),
      text('client', 'Client', { width: 'half', group: 'content', maxLength: 80 }),
      bool('client_public', 'Show client name publicly', { width: 'third', default: true, group: 'content' }),
      text('role', 'Your role', { width: 'half', group: 'content', maxLength: 80, placeholder: 'Shot, edited, graded' }),
      area('problem', 'Brief / challenge', { rows: 4, maxLength: 1200, group: 'content', help: 'Only facts you can stand behind.' }),
      area('solution', 'Approach & execution', { rows: 5, maxLength: 1800, group: 'content' }),
      list('outcomes', 'Outcomes', { group: 'content', help: 'Verified results only. Leave empty rather than inventing numbers.' }),
      tags('services', 'Services provided', { group: 'content', free: true, options: MEDIA_SERVICE_OPTIONS.map((o) => ({ value: o.value, label: o.label })) }),
      tags('tools', 'Tools', { group: 'content', help: 'Camera bodies, lenses, software.' }),
      list('deliverables', 'Deliverables', { group: 'content' }),
      tags('technologies', 'Techniques / tags', { group: 'content' }),
      { key: 'cover_asset_id', label: 'Cover image', type: 'image', group: 'media' },
      { key: 'hero_video_id', label: 'Lead video', type: 'relation', module: 'videos', width: 'half', group: 'media' },
      {
        key: 'gallery',
        label: 'Gallery',
        type: 'repeat',
        group: 'media',
        itemLabel: 'Frame',
        max: 60,
        itemFields: galleryItemFields,
      },
      { key: 'event_date', label: 'Event date', type: 'date', width: 'third', group: 'details' },
      num('year', 'Year', { width: 'third', group: 'details', min: 2000, max: 2100 }),
      text('location', 'Location', { width: 'third', group: 'details' }),
      text('duration_label', 'Runtime', { width: 'third', group: 'details', placeholder: '3:42', maxLength: 20 }),
      text('budget_band', 'Budget band', { width: 'third', group: 'details', maxLength: 60, help: 'Optional internal note; never published unless you mark it.' }),
      text('accent', 'Accent colour override', { width: 'third', group: 'details' }),
      {
        key: 'external_links',
        label: 'Published links',
        type: 'repeat',
        group: 'links',
        itemLabel: 'Link',
        max: 12,
        itemFields: externalLinkFields,
      },
      {
        key: 'credits',
        label: 'Credits',
        type: 'repeat',
        group: 'links',
        itemLabel: 'Credit',
        max: 20,
        itemFields: [text('role', 'Role', { required: true, maxLength: 40 }), text('name', 'Name', { maxLength: 60 })],
      },
      {
        key: 'metrics',
        label: 'Metrics',
        type: 'repeat',
        group: 'content',
        itemLabel: 'Metric',
        max: 8,
        itemFields: [
          text('label', 'Label', { required: true, maxLength: 40 }),
          text('value', 'Value', { required: true, maxLength: 40 }),
          bool('verified', 'Verified (shown publicly)', { default: false, help: 'Unverified metrics stay private.' }),
        ],
      },
      sampleField(),
      seoField(),
    ],
  },
  {
    key: 'videos',
    label: 'Videos',
    singular: 'Video',
    group: 'Media',
    icon: 'video',
    description: 'Paste a YouTube / TikTok / Facebook / Vimeo URL or upload a file. Metadata is detected where the platform allows it and always editable.',
    table: 'media_video',
    editor: 'videos',
    primary: 'title',
    secondary: 'source',
    previewImage: 'poster_asset_id',
    sortable: true,
    publishable: true,
    slugFrom: 'title',
    filterBy: [
      { key: 'form', label: 'Format', options: VIDEO_FORM_OPTIONS },
      { key: 'source', label: 'Source', options: EMBED_SOURCES },
    ],
    columns: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'source', label: 'Source', type: 'tag' },
      { key: 'form', label: 'Format', type: 'tag' },
      { key: 'is_featured', label: 'Featured', type: 'bool' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'description', 'client'],
    defaultSort: 'ORDER BY sort_order ASC, created_at DESC',
    emptyTitle: 'No videos yet',
    emptyHint: 'Paste a link in the editor and the platform detects the source and poster automatically.',
    fields: [
      { key: 'source_url', label: 'Paste video URL', type: 'text', required: true, help: 'YouTube, TikTok, Facebook, Vimeo, Instagram or a direct https:// video file.' },
      text('title', 'Title', { required: true, maxLength: 120 }),
      area('description', 'Description', { rows: 4, maxLength: 1200 }),
      { key: 'project_id', label: 'Project', type: 'relation', module: 'media_projects', width: 'half' },
      { key: 'category', label: 'Category', type: 'select', width: 'third', options: MEDIA_CATEGORIES.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'form', label: 'Format', type: 'select', width: 'third', options: VIDEO_FORM_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      text('client', 'Client', { width: 'half', maxLength: 80 }),
      { key: 'shot_on', label: 'Shot on', type: 'date', width: 'third' },
      num('duration_s', 'Duration (seconds)', { width: 'third' }),
      { key: 'poster_asset_id', label: 'Poster image', type: 'image', width: 'half', help: 'Shown before playback. Falls back to the platform thumbnail when empty.' },
      { key: 'file_asset_id', label: 'Uploaded file', type: 'asset', width: 'half', help: 'For direct uploads only.' },
      tags('services', 'Services', { group: 'details' }),
      tags('tools', 'Tools', { group: 'details' }),
      tags('tags', 'Tags', { group: 'details' }),
      { key: 'embed_config', label: 'Embed options', type: 'json', group: 'details', help: 'Player parameters derived from the URL; editable.' },
      text('external_url', 'Fallback link', { width: 'half', group: 'details', help: 'Where to send visitors if embedding is not permitted.' }),
      featuredField('Featured in hero / showcase'),
      sampleField(),
      statusField(),
      orderField,
      seoField(),
    ],
  },
  {
    key: 'photos',
    label: 'Photos',
    singular: 'Photo set',
    group: 'Media',
    icon: 'camera',
    description: 'Curated stills sets shown in the Media portfolio gallery.',
    table: 'gallery',
    editor: 'collection',
    primary: 'title',
    secondary: 'kind',
    sortable: true,
    publishable: true,
    slugFrom: 'title',
    fixed: { kind: 'photo', division: 'media' },
    columns: [
      { key: 'title', label: 'Gallery', type: 'text' },
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'description'],
    publicBase: '/media/work/gallery/',
    fields: [
      text('title', 'Title', { required: true, maxLength: 100 }),
      slug('slug', 'Slug', { required: true }),
      area('description', 'Description', { rows: 3, maxLength: 500 }),
      statusField(),
      featuredField(),
      orderField,
      {
        key: 'items',
        label: 'Photos',
        type: 'repeat',
        group: 'media',
        itemLabel: 'Photo',
        max: 120,
        itemFields: galleryItemFields,
      },
      { key: 'project_id', label: 'Related project', type: 'relation', module: 'media_projects', group: 'media', width: 'half' },
      sampleField(),
    ],
  },
  {
    key: 'galleries',
    label: 'Galleries',
    singular: 'Gallery',
    group: 'Media',
    icon: 'gallery',
    description: 'Mixed photo/video collections for any experience.',
    table: 'gallery',
    editor: 'collection',
    primary: 'title',
    secondary: 'slug',
    sortable: true,
    publishable: true,
    slugFrom: 'title',
    filterBy: { key: 'division', label: 'Division', options: DIVISION_OPTIONS },
    columns: [
      { key: 'title', label: 'Gallery', type: 'text' },
      { key: 'kind', label: 'Kind', type: 'tag' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'description'],
    publicBase: '/work/gallery/',
    fields: [
      text('title', 'Title', { required: true, maxLength: 100 }),
      slug('slug', 'Slug', { required: true }),
      { key: 'division', label: 'Division', type: 'select', width: 'third', default: 'media', options: DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'kind', label: 'Content', type: 'select', width: 'third', default: 'photo', options: [{ value: 'photo', label: 'Photos' }, { value: 'video', label: 'Videos' }, { value: 'mixed', label: 'Mixed' }] },
      statusField(),
      featuredField(),
      orderField,
      area('description', 'Description', { rows: 3, maxLength: 500 }),
      { key: 'project_id', label: 'Related project', type: 'relation', module: 'media_projects', width: 'half' },
      {
        key: 'items',
        label: 'Items',
        type: 'repeat',
        group: 'media',
        itemLabel: 'Item',
        max: 120,
        itemFields: galleryItemFields,
      },
      sampleField(),
    ],
  },
  {
    key: 'media_library',
    label: 'Media library',
    singular: 'Asset',
    group: 'Media',
    icon: 'library',
    description: 'Every uploaded image, video and document. Alt text, captions, folders and safe replacement live here.',
    table: 'media_asset',
    editor: 'media-library',
    primary: 'title',
    secondary: 'filename',
    columns: [{ key: 'filename', label: 'File', type: 'text' }],
    search: ['filename', 'title', 'alt', 'caption', 'folder'],
    fields: [
      text('title', 'Title', { maxLength: 120 }),
      text('alt', 'Alt text', { maxLength: 200, help: 'Required for meaningful images.' }),
      area('caption', 'Caption', { rows: 2, maxLength: 240 }),
      text('credit', 'Credit', { width: 'half', maxLength: 80 }),
      text('folder', 'Folder', { width: 'half', maxLength: 80 }),
      tags('tags', 'Tags', {}),
    ],
  },

  // ── Technology ───────────────────────────────────────────────────────────
  {
    key: 'tech_projects',
    label: 'Tech projects',
    singular: 'Tech project',
    group: 'Technology',
    icon: 'code',
    description: 'Software, product and security work with problem → solution → outcome and links to repos or demos.',
    table: 'project',
    editor: 'projects',
    primary: 'title',
    secondary: 'category',
    previewImage: 'cover_asset_id',
    sortable: true,
    publishable: true,
    slugFrom: 'title',
    duplicate: true,
    fixed: { division: 'tech' },
    filterBy: { key: 'category', label: 'Category', options: TECH_CATEGORIES },
    columns: [
      { key: 'title', label: 'Project', type: 'text' },
      { key: 'category', label: 'Category', type: 'tag' },
      { key: 'year', label: 'Year', type: 'number' },
      { key: 'is_featured', label: 'Featured', type: 'bool' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'summary', 'client', 'role'],
    publicBase: '/tech/projects/',
    emptyTitle: 'No tech projects yet',
    emptyHint: 'Add PalKeeper, CStudio AI, dashboards, apps and security engagements as you document them.',
    fields: [
      text('title', 'Title', { required: true, maxLength: 120 }),
      slug('slug', 'Slug', { required: true }),
      { key: 'division', label: 'Portfolio', type: 'select', required: true, width: 'third', default: 'tech', options: PORTFOLIO_DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'category', label: 'Category', type: 'select', width: 'third', options: TECH_CATEGORIES.map((o) => ({ value: o.value, label: o.label })) },
      statusField(),
      featuredField(),
      orderField,
      area('summary', 'One-line summary', { rows: 3, maxLength: 260, group: 'content' }),
      text('role', 'Your role', { width: 'half', group: 'content', maxLength: 80 }),
      text('client', 'Client / org', { width: 'half', group: 'content', maxLength: 80 }),
      bool('client_public', 'Show client name publicly', { width: 'third', default: true, group: 'content' }),
      area('problem', 'Problem', { rows: 4, maxLength: 1500, group: 'content' }),
      area('solution', 'Solution', { rows: 5, maxLength: 2000, group: 'content' }),
      list('outcomes', 'Outcomes', { group: 'content', help: 'Only measured results. Leave blank rather than inventing figures.' }),
      tags('technologies', 'Technologies', { group: 'content', free: true }),
      tags('services', 'Disciplines', { group: 'content', free: true }),
      tags('tools', 'Tooling', { group: 'content' }),
      list('deliverables', 'Deliverables', { group: 'content' }),
      {
        key: 'metrics',
        label: 'Metrics',
        type: 'repeat',
        group: 'content',
        itemLabel: 'Metric',
        max: 8,
        itemFields: [
          text('label', 'Label', { required: true, maxLength: 40 }),
          text('value', 'Value', { required: true, maxLength: 40 }),
          bool('verified', 'Verified (shown publicly)', { default: false }),
        ],
      },
      { key: 'repo_url', label: 'Repository', type: 'url', width: 'half', group: 'links' },
      { key: 'live_url', label: 'Live demo', type: 'url', width: 'half', group: 'links' },
      { key: 'case_study_url', label: 'Long write-up', type: 'url', width: 'half', group: 'links' },
      { key: 'external_links', label: 'Other links', type: 'repeat', group: 'links', itemLabel: 'Link', max: 12, itemFields: externalLinkFields },
      { key: 'cover_asset_id', label: 'Cover / hero image', type: 'image', group: 'media' },
      { key: 'gallery', label: 'Screenshots', type: 'repeat', group: 'media', itemLabel: 'Screenshot', max: 30, itemFields: galleryItemFields },
      num('year', 'Year', { width: 'third', group: 'details', min: 2000, max: 2100 }),
      { key: 'event_date', label: 'Start date', type: 'date', width: 'third', group: 'details' },
      text('location', 'Context / org location', { width: 'third', group: 'details' }),
      text('duration_label', 'Duration', { width: 'third', group: 'details', maxLength: 40 }),
      text('accent', 'Accent colour override', { width: 'third', group: 'details' }),
      sampleField(),
      seoField(),
    ],
  },
  {
    key: 'skills',
    label: 'Skills',
    singular: 'Skill',
    group: 'Technology',
    icon: 'skills',
    description: 'The capability matrix shown on the Tech portfolio. "Evidence" keeps every claim honest.',
    table: 'skill',
    editor: 'collection',
    primary: 'name',
    secondary: 'category',
    sortable: true,
    publishable: true,
    slugFrom: 'name',
    filterBy: { key: 'category', label: 'Category', options: SKILL_CATEGORIES },
    columns: [
      { key: 'name', label: 'Skill', type: 'text' },
      { key: 'category', label: 'Category', type: 'tag' },
      { key: 'level', label: 'Depth', type: 'number' },
      { key: 'is_featured', label: 'Featured', type: 'bool' },
    ],
    search: ['name', 'description', 'evidence'],
    fields: [
      text('name', 'Skill', { required: true, maxLength: 60 }),
      slug('slug', 'Slug', { required: true }),
      { key: 'category', label: 'Category', type: 'select', width: 'third', default: 'frontend', options: SKILL_CATEGORIES.map((o) => ({ value: o.value, label: o.label })) },
      num('level', 'Depth (1–5)', { width: 'third', min: 1, max: 5, default: 3, help: 'Self-described depth used for the meter, not a certification.' }),
      num('confidence', 'Confidence (1–5)', { width: 'third', min: 1, max: 5 }),
      statusField(),
      featuredField('Feature in highlights'),
      orderField,
      area('description', 'What you do with it', { rows: 3, maxLength: 300 }),
      text('evidence', 'Evidence', { maxLength: 200, help: 'Project name, repo or role that backs the claim.' }),
      num('years_start', 'Working with it since', { width: 'third', min: 1990, max: 2100 }),
      text('icon', 'Icon', { width: 'third', maxLength: 40 }),
      sampleField(),
    ],
  },
  {
    key: 'experience',
    label: 'Experience',
    singular: 'Experience entry',
    group: 'Technology',
    icon: 'timeline',
    description: 'Chronological timeline for the Tech portfolio (PRD §8: begins around 2015, details editable).',
    table: 'experience_item',
    editor: 'collection',
    primary: 'role',
    secondary: 'organization',
    sortable: true,
    publishable: true,
    columns: [
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'organization', label: 'Organisation', type: 'text' },
      { key: 'start_label', label: 'From', type: 'text' },
      { key: 'is_current', label: 'Current', type: 'bool' },
    ],
    search: ['role', 'organization', 'summary'],
    defaultSort: 'ORDER BY sort_order DESC, start_date DESC NULLS LAST',
    fields: [
      text('role', 'Role / title', { required: true, maxLength: 100 }),
      text('organization', 'Organisation', { width: 'half', maxLength: 100 }),
      text('location', 'Location', { width: 'half', maxLength: 80 }),
      { key: 'kind', label: 'Type', type: 'select', width: 'third', default: 'work', options: EXPERIENCE_KINDS.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'start_date', label: 'Start', type: 'date', width: 'third' },
      text('start_label', 'Start label', { width: 'third', maxLength: 30, placeholder: '2015' }),
      { key: 'end_date', label: 'End', type: 'date', width: 'third' },
      text('end_label', 'End label', { width: 'third', maxLength: 30, placeholder: 'Present' }),
      bool('is_current', 'Current', { width: 'third' }),
      area('summary', 'Summary', { rows: 3, maxLength: 600, group: 'content' }),
      list('bullets', 'Responsibilities', { group: 'content' }),
      list('highlights', 'Highlights', { group: 'content', help: 'Verified results only.' }),
      tags('technologies', 'Stack', { group: 'content' }),
      { key: 'project_ids', label: 'Related projects', type: 'relation', module: 'tech_projects', group: 'content', multiple: true } as FieldDef,
      sampleField(),
      statusField(),
      orderField,
    ],
  },
  {
    key: 'certifications',
    label: 'Certifications',
    singular: 'Certification',
    group: 'Technology',
    icon: 'shield',
    description: 'Only completed, verifiable credentials appear as earned. In-progress items are labelled as such.',
    table: 'certification',
    editor: 'collection',
    primary: 'name',
    secondary: 'issuer',
    sortable: true,
    columns: [
      { key: 'name', label: 'Credential', type: 'text' },
      { key: 'issuer', label: 'Issuer', type: 'text' },
      { key: 'status', label: 'Status', type: 'tag' },
      { key: 'completed', label: 'Completed', type: 'bool' },
    ],
    search: ['name', 'issuer'],
    fields: [
      text('name', 'Credential name', { required: true, maxLength: 120 }),
      text('issuer', 'Issuer', { width: 'half', maxLength: 80 }),
      { key: 'status', label: 'Public status', type: 'select', width: 'third', default: 'in_progress', options: CERTIFICATION_STATUSES.map((o) => ({ value: o.value, label: o.label })) },
      bool('completed', 'Actually completed', { width: 'third', help: 'Must be true AND verifiable for the card to render as "Earned".' }),
      { key: 'issued_on', label: 'Issued', type: 'date', width: 'third' },
      { key: 'expires_on', label: 'Expires', type: 'date', width: 'third' },
      text('credential_id', 'Credential ID', { width: 'half', maxLength: 80 }),
      { key: 'verify_url', label: 'Verification URL', type: 'url', width: 'half' },
      text('status_label_override', 'Custom status label', { width: 'half', maxLength: 40, placeholder: 'Exam scheduled — Mar 2026' }),
      area('description', 'Notes', { rows: 3, maxLength: 400 }),
      orderField,
    ],
    emptyHint: 'Nothing here yet — the Tech portfolio hides this section until you add real credentials.',
  },
  {
    key: 'resume',
    label: 'Resume',
    singular: 'Resume version',
    group: 'Technology',
    icon: 'resume',
    description: 'Upload a PDF, mark one version active. The public download button disappears when nothing is published.',
    table: 'resume_version',
    editor: 'resume',
    primary: 'label',
    secondary: 'version',
    columns: [
      { key: 'label', label: 'Version', type: 'text' },
      { key: 'is_active', label: 'Active', type: 'bool' },
      { key: 'published_at', label: 'Published', type: 'date' },
    ],
    search: ['label', 'version'],
    fields: [
      text('label', 'Label', { required: true, maxLength: 80, placeholder: 'Covenant Nsikan — General' }),
      text('version', 'Version', { width: 'third', maxLength: 30, placeholder: '1.0' }),
      { key: 'asset_id', label: 'PDF file', type: 'asset', width: 'half' },
      bool('is_active', 'Active download', { width: 'third', help: 'Exactly one version should be active.' }),
      { key: 'published_at', label: 'Published on', type: 'date', width: 'third' },
      area('notes', 'Internal notes', { rows: 2, maxLength: 300 }),
    ],
    emptyHint: 'Upload a PDF to reveal the resume section on the Tech portfolio.',
  },

  // ── Commerce ───────────────────────────────────────────────────────────────
  {
    key: 'pricing',
    label: 'Pricing',
    singular: 'Package',
    group: 'Commerce',
    icon: 'pricing',
    description: 'Packages, starting prices or quote-only. No price exists until Covenant enters one.',
    table: 'pricing_package',
    editor: 'collection',
    primary: 'name',
    secondary: 'mode',
    sortable: true,
    publishable: true,
    filterBy: { key: 'division', label: 'Division', options: PORTFOLIO_DIVISION_OPTIONS },
    columns: [
      { key: 'name', label: 'Package', type: 'text' },
      { key: 'division', label: 'Division', type: 'tag' },
      { key: 'mode', label: 'Mode', type: 'tag' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['name', 'tagline', 'notes'],
    publicBase: '/media/pricing',
    emptyTitle: 'No pricing published',
    emptyHint: 'The Media pricing page then shows a quote-first message instead of invented numbers.',
    fields: [
      text('name', 'Package name', { required: true, maxLength: 80 }),
      text('tagline', 'Tagline', { maxLength: 140 }),
      { key: 'division', label: 'Division', type: 'select', width: 'third', default: 'media', options: PORTFOLIO_DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'mode', label: 'Price mode', type: 'select', width: 'third', default: 'quote', options: PRICING_MODES.map((o) => ({ value: o.value, label: o.label })) },
      { key: 'amount', label: 'Amount', type: 'money', width: 'third', min: 0, showIf: { key: 'mode', equals: ['fixed', 'starting_at', 'day_rate'] } },
      { key: 'currency', label: 'Currency', type: 'select', width: 'third', default: 'NGN', options: CURRENCY_OPTIONS.map((o) => ({ value: o.value, label: o.label })), showIf: { key: 'mode', equals: ['fixed', 'starting_at', 'day_rate'] } },
      { key: 'period', label: 'Period', type: 'select', width: 'third', options: PRICING_PERIODS.map((o) => ({ value: o.value, label: o.label })), showIf: { key: 'mode', equals: ['fixed', 'starting_at', 'day_rate'] } },
      statusField(),
      featuredField('Highlight this tier'),
      orderField,
      list('includes', 'What is included', { group: 'content' }),
      list('exclusions', 'Not included', { group: 'content' }),
      text('turnaround', 'Typical turnaround', { width: 'half', group: 'content', maxLength: 60 }),
      area('notes', 'Notes / fine print', { rows: 3, maxLength: 500, group: 'content' }),
      sampleField(),
    ],
  },
  {
    key: 'contact_info',
    label: 'Contact information',
    singular: 'Contact setting',
    group: 'Commerce',
    icon: 'mail',
    description: 'Email, phone, WhatsApp, response promise and form behaviour used by every public form.',
    table: 'site_setting',
    editor: 'settings',
    primary: 'label',
    columns: [{ key: 'key', label: 'Key', type: 'text' }],
    fields: [text('key', 'Key', { required: true })],
  },

  // ── Insight ────────────────────────────────────────────────────────────────
  {
    key: 'blog',
    label: 'Blog',
    singular: 'Article',
    group: 'Insight',
    icon: 'blog',
    description: 'Articles for both disciplines: tutorials, breakdowns, security notes, behind the scenes.',
    table: 'blog_post',
    editor: 'collection',
    primary: 'title',
    secondary: 'category',
    previewImage: 'cover_asset_id',
    sortable: false,
    publishable: true,
    slugFrom: 'title',
    duplicate: true,
    filterBy: { key: 'division', label: 'Division', options: DIVISION_OPTIONS },
    columns: [
      { key: 'title', label: 'Article', type: 'text' },
      { key: 'category', label: 'Category', type: 'tag' },
      { key: 'published_at', label: 'Published', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    search: ['title', 'excerpt', 'body'],
    publicBase: '/blog/',
    defaultSort: 'ORDER BY COALESCE(published_at, created_at) DESC',
    emptyHint: 'Write the first breakdown — even one strong article beats an empty list.',
    fields: [
      text('title', 'Title', { required: true, maxLength: 140 }),
      slug('slug', 'Slug', { required: true }),
      statusField(PUBLISH_OPTIONS),
      area('excerpt', 'Excerpt', { rows: 3, maxLength: 320, group: 'content' }),
      { key: 'body', label: 'Article body', type: 'markdown', rows: 24, group: 'content', help: 'Markdown. Headings, lists, quotes, code blocks and links are sanitised on save.' },
      { key: 'cover_asset_id', label: 'Cover image', type: 'image', group: 'media' },
      { key: 'author_name', label: 'Author', type: 'text', width: 'half', group: 'meta', maxLength: 80 },
      { key: 'division', label: 'Appears in', type: 'select', width: 'third', group: 'meta', default: 'main', options: DIVISION_OPTIONS.map((o) => ({ value: o.value, label: o.label })) },
      text('category', 'Category', { width: 'third', group: 'meta', maxLength: 60, placeholder: 'Cybersecurity' }),
      tags('tags', 'Tags', { group: 'meta' }),
      { key: 'related_project_ids', label: 'Related projects', type: 'relation', module: 'media_projects', group: 'meta', width: 'half', multiple: true } as FieldDef,
      { key: 'published_at', label: 'Publish date', type: 'datetime', width: 'third', group: 'meta' },
      { key: 'scheduled_at', label: 'Schedule for', type: 'datetime', width: 'third', group: 'meta', help: 'Future date + scheduled status = auto-publishes when due.' },
      sampleField(),
      seoField(),
    ],
  },

  // ── System ─────────────────────────────────────────────────────────────────
  {
    key: 'seo',
    label: 'SEO',
    singular: 'SEO record',
    group: 'System',
    icon: 'search',
    description: 'Per-page titles, descriptions, canonicals, robots and social cards.',
    table: 'seo_record',
    editor: 'seo',
    primary: 'scope',
    columns: [{ key: 'scope', label: 'Scope', type: 'text' }],
    fields: [
      text('scope', 'Scope', { required: true }),
      text('title', 'Title', { maxLength: 70 }),
      text('description', 'Description', { maxLength: 200 }),
    ],
  },
  {
    key: 'submissions',
    label: 'Contact submissions',
    singular: 'Submission',
    group: 'System',
    icon: 'inbox',
    description: 'Every enquiry from all three public forms, with status triage and CSV export.',
    table: 'contact_submission',
    editor: 'submissions',
    primary: 'name',
    secondary: 'email',
    columns: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'form', label: 'Form', type: 'tag' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'created_at', label: 'Received', type: 'date' },
    ],
    search: ['name', 'email', 'message', 'organization'],
    defaultSort: 'ORDER BY created_at DESC',
    fields: [
      { key: 'status', label: 'Status', type: 'select', default: 'new', options: [{ value: 'new', label: 'New' }, { value: 'read', label: 'Read' }, { value: 'replied', label: 'Replied' }, { value: 'archived', label: 'Archived' }, { value: 'spam', label: 'Spam' }] },
    ],
  },
  {
    key: 'featured',
    label: 'Featured content',
    singular: 'Featured item',
    group: 'System',
    icon: 'star',
    description: 'One screen to decide what the homepages, showcases and hero rails show.',
    table: 'project',
    editor: 'featured',
    primary: 'title',
    columns: [{ key: 'title', label: 'Title', type: 'text' }],
    fields: [],
  },
];

export const CMS_MODULE_MAP: Record<string, CmsModuleDef> = Object.fromEntries(CMS_MODULES.map((m) => [m.key, m]));

export function getCmsModule(key: string): CmsModuleDef | undefined {
  return CMS_MODULE_MAP[key];
}

export const MODULE_GROUPS: { key: ModuleGroup; label: string; hint: string }[] = [
  { key: 'Structure', label: 'Site structure', hint: 'Pages, sections and menus' },
  { key: 'Brand', label: 'Brand & services', hint: 'Positioning, services, socials' },
  { key: 'Media', label: 'Media portfolio', hint: 'Projects, videos, photo sets' },
  { key: 'Technology', label: 'Tech portfolio', hint: 'Projects, skills, resume, credentials' },
  { key: 'Trust', label: 'People & proof', hint: 'Testimonials and team' },
  { key: 'Commerce', label: 'Commercial', hint: 'Pricing and contact routing' },
  { key: 'Insight', label: 'Writing', hint: 'Blog and breakdowns' },
  { key: 'System', label: 'System', hint: 'SEO, leads, cross-cutting' },
];
