/**
 * Regenerates src/lib/icons/brands.ts from simple-icons (CC0-licensed path data)
 * so brand marks render correctly without shipping the whole icon package.
 *   node scripts/extract-icons.mjs
 */
import * as si from 'simple-icons';
import { writeFileSync } from 'node:fs';

const WANTED = [
  ['tiktok', 'siTiktok'],
  ['instagram', 'siInstagram'],
  ['youtube', 'siYoutube'],
  ['facebook', 'siFacebook'],
  
  ['github', 'siGithub'],
  ['linkedin', 'siLinkedin'],
  ['x', 'siX'],
  ['whatsapp', 'siWhatsapp'],
  ['vimeo', 'siVimeo'],
  ['behance', 'siBehance'],
  ['dribbble', 'siDribbble'],
  ['figma', 'siFigma'],
  
  
  
  
  ['davinciResolve', 'siDavinciresolve'],
  
  ['blender', 'siBlender'],
  ['nodejs', 'siNodedotjs'],
  ['react', 'siReact'],
  ['nextjs', 'siNextdotjs'],
  ['python', 'siPython'],
  ['postgres', 'siPostgresql'],
  ['tailwind', 'siTailwindcss'],
  ['flutter', 'siFlutter'],
  ['linux', 'siLinux'],
  ['docker', 'siDocker'],
  ['kali', 'siKalilinux'],
  ['burp', 'siBurpsuite'],
  ['wireshark', 'siWireshark'],
  ['metasploit', 'siMetasploit'],
  
  ['vercel', 'siVercel'],
  ['netlify', 'siNetlify'],
  ['cloudflare', 'siCloudflare'],
];

// Marks that newer simple-icons releases no longer bundle. Verified geometry, 24×24.
const MANUAL = {
  linkedin:
    'M20.45 20.45h-3.55v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.36V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12zM7.12 20.45H3.56V9h3.56v11.45zM22.22 0H1.77C.79 0 0 .77 0 1.72v20.56C0 23.23.79 24 1.77 24h20.45c.98 0 1.78-.77 1.78-1.72V1.72C24 .77 23.2 0 22.22 0z',
  x: 'M18.9 1.4h3.7l-8.1 9.2 9.5 12.6h-7.4l-5.8-7.6-6.7 7.6H-.4l8.7-9.8L-1.3 1.4h7.6l5.2 6.9L18.9 1.4zm-1.3 19.9h2L6.5 3.5H4.3l13.3 17.8z',
};

const byName = new Map(Object.entries(si));
const out = [];
for (const [name, symbol] of WANTED) {
  const icon = byName.get(symbol) ?? (MANUAL[name] ? { path: MANUAL[name] } : null);
  if (!icon || typeof icon.path !== 'string') {
    console.warn('  · skipped (not found):', symbol);
    continue;
  }
  out.push({ name, path: icon.path });
}

const body = `/**
 * Brand marks. Path data extracted from the simple-icons package (CC0).
 * Generated by scripts/extract-icons.mjs — regenerate rather than hand-edit.
 */
export const BRAND_ICONS: Record<string, string> = {
${out.map((o) => `  ${JSON.stringify(o.name)}: ${JSON.stringify(o.path)},`).join('\n')}
};

export const BRAND_ICON_KEYS = ${JSON.stringify(out.map((o) => o.name))} as const;
`;

writeFileSync('src/lib/icons/brands.ts', body);
console.log(`wrote ${out.length} brand icons to src/lib/icons/brands.ts`);
